# Generated by Django 6.0.3 on 2026-03-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RunSQL(
            """
            INSERT OR IGNORE INTO someap_category (name, description)
            SELECT DISTINCT category, '' FROM someap_product WHERE category IS NOT NULL AND category != '';
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AddField(
            model_name='product',
            name='category_temp',
            field=models.ForeignKey('someap.Category', on_delete=models.CASCADE, null=True),
        ),
        migrations.RunSQL(
            """
            UPDATE someap_product
            SET category_temp_id = (SELECT id FROM someap_category WHERE name = someap_product.category)
            WHERE category IS NOT NULL AND category != '';
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_temp',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey('someap.Category', on_delete=models.CASCADE),
        ),
        migrations.RemoveField(
            model_name='product',
            name='low_stock_threshold',
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_limit',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
